### ISSUE TITLE
Implementation in cakePHP 3

### ISSUE THREAD

**Issue by mohinithorat** [CakeDC/TinyMCE#49] opened 2017-02-08 05:40 UTC
Hello Team,

Can you guide me to implement this plugin in cakePHP 3?

Thanks in advance.

**Comment by yeliparra** [comment] 2017-02-13 14:43
Hello @mohinithorat, there is a branch for version 3, switch to branch 3.x for using it.

**Comment by Megslalk** [comment] 2017-02-13 15:01
Closing this issue - please re-open if you require further assistance!

**Closed by Megslalk** 2017-02-13 15:01 UTC

**Comment by meDeepakJain** [comment] 2017-10-18 05:56
@Megslalk I have used composer's way to install tinymce. And, it has been successfully downloaded to vendor folder. While all docs define patterns of using it via plugins. Why is it so? Why is it not working as intended if it is installed on vendor?
